# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote-docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            -  Terraform/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn ng build --prod
      - run: yarn ng test --watch=false

      # Terraform Build VM

      - run:
          path:
            - /Terraform/Create_VM
          command: |
            terraform init
      - run:
          path:
            - /Terraform/Create_VM
          command: |
            terraform plan
      - run:
          path:
            - /Terraform/Create_VM
          command: |
            terraform apply


    # Docker Image Build
      - run:
          command: |
            docker image build -t mydevreg.azurecr.io/hero-cicd:2.0 .
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS mydevreg.azurecr.io
      - run:
          command: |
            docker push mydevreg.azurecr.io/hero-cicd:2.0



